### ISSUE TITLE
Remove smiles.txt

### ISSUE THREAD

**Issue by kelson42** [cheminfo/wikipedia#23]
Wouldn't be better to simply make a data.json CSV exporter?

**Comment by lpatiny** [comment]
We wanted to provide a smiles.txt so that other application can directly use an daily updated file. One application that use it is DataWarrior.
We also don't want to put any "logic" on the server so that you can from github simply clone the project on an apache webserver and that it provides the file. It seems that create a CSV exporter would involve some PHP or nodeJS script on the server that is always more difficult to install.
This is why we generate the 2 files.
Also a big advantage of this SMILES file is that the diff shows us directly the added / removed SMILES entries in wikipedia.

**Comment by peter-ertl** [comment]
Fully agree, and additionally, the address smiles.txt (and the link) are
mentioned in the article, so people would expect to find this file.
p
